### PR TITLE
Migrate to @blueprintjs/popover2

### PR DESCRIPTION
**Pull request by gjvoosten**
Migrate Popover and Tooltip to the new Popover2 and Tooltip2.

Closes NCI-Agency/anet#3410

#### User changes
- In addition to the changed library underneath (which should be mostly invisible to the user, with the exception of some slightly improved positioning of pop-ups), it is now also possible to change the search text while building up search filters. Previously, clicking in the text box (or anywhere else outside the filter pop-up for that matter) while adding filters would dismiss the filter pop-up, which removed any changes to the filters. Starting with this version, dismissing the filter pop-up (without applying the changes) should now be done by clicking the Cancel button in the filter pop-up or by clicking on the textual representation of the current filter (just underneath the search text input).

#### Super User changes
- none

#### Admin changes
- none

#### System admin changes
- [ ] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [x] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [x] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

### CODE REVIEW

**Review by cemalettin-simsoft — APPROVED** [review]
It should be noted that when the new major version is introduced, Popover2s and Tooltip2s will be the default with ,probably, the original names Popover and Tooltip. So, we will need to change the names again but not the api/props.

**Comment by gjvoosten** [comment]
> It should be noted that when the new major version is introduced, Popover2s and Tooltip2s will be the default with ,probably, the original names Popover and Tooltip. So, we will need to change the names again but not the api/props.

It's not clear to me whether they will change the names back, I couldn't find any indication of that.

**Comment by cemalettin-simsoft** [comment]
> > It should be noted that when the new major version is introduced, Popover2s and Tooltip2s will be the default with ,probably, the original names Popover and Tooltip. So, we will need to change the names again but not the api/props.
> 
> It's not clear to me whether they will change the names back, I couldn't find any indication of that.

From the migration docs, it says these will be the defaults, which i assumed that. Having Popover2, Popover3 etc wouldn't be sensible, as this is what versioning a package is for.

**Comment by gjvoosten** [comment]
> From the migration docs, it says these will be the defaults, which i assumed that. Having Popover2, Popover3 etc wouldn't be sensible, as this is what versioning a package is for.

Note: the package _is_ called `@blueprintjs/popover2` so _iff_ they are going to change the names (and I'm not convinced they will), the package name would probably change as well.

**Pull request merged**
