### PR TITLE
WIP: Do not fail if ShiftLeft finds only the known 4 false positives

### PR DESCRIPTION
**Pull request by gjvoosten**

### CODE REVIEW

**Comment by prabhu** [comment]
Hi @gjvoosten 

Noticed that you were trying to configure the default break logic but using the configuration of our commercial product. The configuration for Scan is different.

As shown here: https://slscan.io/en/latest/integrations/tips/#config-file

Create a local file called .sastscanrc with the following contents.

```json
{
  "build_break_rules": {
    "default": {"max_critical": 2, "max_high": 5, "max_medium": 15}
  }
}
```

In addition, there is also support for suppression - https://slscan.io/en/latest/getting-started/#suppression

Let me know if any of this would work for you.

**Comment by prabhu** [comment]
In addition, I have disabled the default behavior to mark PR as failure automatically based on findings.

**Comment by gjvoosten** [comment]
> In addition, there is also support for suppression - https://slscan.io/en/latest/getting-started/#suppression

@prabhu But that only works for the Java source code analyzer, which reports 0 issues for us; it doesn't work for the class file analyzer (where the false positives are reported), as comments are not preserved there, right?

**Comment by gjvoosten** [comment]
> @gjvoosten it should work for all analyzers if the comment is on the same line or above. The cli would take the information from the analyzer and would go check the raw source code since it is available in the pipeline.

@prabhu What am I missing? It still reports the line with `// scan:ignore`, see screenshot.
Screenshot from 2020-08-17 08-32-04

**Comment by prabhu** [comment]
@gjvoosten Glad you found the issue.

**Pull request closed without merging**
