### PR TITLE
Show organizations and positions at a location

### PR DESCRIPTION
**Pull request by gjvoosten**
The location details page now has sections showing the organizations and positions at this location.

Closes [AB#1164](https://dev.azure.com/ncia-anet/2aa083a5-af3d-44e1-8c7b-6e9e6b124d91/_workitems/edit/1164)

#### User changes
- A user can see the organizations and positions at a location.
- The search results for organizations now also show the organization's location.

#### Superuser changes
- None.

#### Admin changes
- None.

#### System admin changes
- [ ] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [x] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [x] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

### CODE REVIEW

**Comment by pacodelcastillolopez** [comment]
There is a typo in the MR description, missing a verb after "A user can"  I believe.

User changes
A user can the organizations and positions at a location.

**Comment by pacodelcastillolopez** [comment]
I dont see any testing for this feature. Maybe a basic one to show that if you click on a location with organizations on it they are displayed. The existing initial data allows this. For example going to "Afghanistan" location we should see MoD, MOD-F and MoI in "Organizations at this location".

**Comment by pacodelcastillolopez** [comment]
I believe there is a change in the code that is not explained in the MR. Now the Position Table can be configured to show or not show the Location with the "showLocation" parameter. Before it was always displayed. Also, unless I overlooked something, this "showLocation" parameter is always passed as true right now so it does not add anything. Maybe this needs to eventually be configured somewhere?

**Comment by gjvoosten** [comment]
> I believe there is a change in the code that is not explained in the MR. Now the Position Table can be configured to show or not show the Location with the "showLocation" parameter. Before it was always displayed. Also, unless I overlooked something, this "showLocation" parameter is always passed as true right now so it does not add anything. Maybe this needs to eventually be configured somewhere?

You are indeed missing something. :wink: The PositionTable is now also shown on the location details page, and showing the position location there makes no sense, as it's totally redundant, so we need the extra prop (and previous inclusions of that table need to be updated with the new prop).

**Comment by gjvoosten** [comment]
> I dont see any testing for this feature. Maybe a basic one to show that if you click on a location with organizations on it they are displayed. The existing initial data allows this. For example going to "Afghanistan" location we should see MoD, MOD-F and MoI in "Organizations at this location".

Added wdio tests.

**Review by pacodelcastillolopez — APPROVED** [review]

**Review by Chessray — APPROVED** [review]

**Pull request merged**
