### PR TITLE
Reserve pinpoint locations term for user pinned location

### LINKED ISSUE #3834: Reserve "pinpoint locations" term for user pinned location
Currently we use the term _pinpoint location_ for a point on the the globe (geodetcial map), as specialiation of physical location:

- physical location
  - pinpoint location
  - area
- virtual location
- 
What we mean with [pinpoint location](https://en.wikipedia.org/wiki/Pinpoint), is point on the map. 

I am concered that [pinpoint location](https://en.wikipedia.org/wiki/Pinpoint) is not easily confused with use custom (user pinned) location on the map.

- physical location
  - point
    - pinpoint
  - area
- virtual location
  
Related:
- #3782

### PR DESCRIPTION
**Pull request by asafkaganbezgin**
All _pinpoint location_ labels are converted into _point location_ both in UI and source code.

Closes #3834

#### User changes
- Should expect to see _point location_ instead of _pinpoint location_.

#### Super User changes
- None

#### Admin changes
- None

#### System admin changes
- [x] anet.yml or anet-dictionary.yml needs change
- [x] db needs migration
- [ ] documentation has changed
- [x] graphql schema has changed

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [ ] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

### CODE REVIEW

**Review by midmarch — COMMENTED** [review]
Where user string representation done of `Location.LOCATION_TYPES` to a string displayed to the user via the GUI?

**Comment by asafkaganbezgin** [comment]
> Where user string representation done of `Location.LOCATION_TYPES` to a string displayed to the user via the GUI?

We have a utility function to convert `LOCATION_TYPE` into `Location Type` in the UI.

**Comment by midmarch** [comment]
> We have a utility function to convert `LOCATION_TYPE` into `Location Type` in the UI.

In that case, maybe better to rename "POINT_LOCATION" to "POINT" so it is displayed as "point" or "Point" to the user.

**Comment by asafkaganbezgin** [comment]
For consistency, we are using `TYPE_LOCATION` format for all location type labels except `Geographical Area`. We should decide if we want to make another exception for `Point location`.

**Review by gjvoosten — APPROVED** [review]

**Pull request merged**
